{
    'name': 'AI-Driven Health Diagnosis for Employees',
    'summary': 'Provides AI-driven preliminary health advice based on employee-reported symptoms via integration with the Odoo HR module.',
    'description': """This module integrates OpenAI's capabilities to offer AI-driven preliminary health advice for employees within the Odoo HR module. Employees can input symptoms and receive possible health advice, enabling companies to support employee well-being and reduce absenteeism.""",
    'author': 'ABDENNACER Elbasri',
    'company': 'Tasyer SOFT',
    'maintainer': 'ABDENNACER Elbasri',
    'category': 'Human Resources',
    'license': 'AGPL-3',
    'images': ['static/description/ai_health_icon.png'],
    'depends': ['base', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'views/report.xml',
        'views/health_diagnosis_views.xml',
        'views/health_diagnosis_attribute_views.xml',
        'views/health_diagnosis_attribute_value_views.xml',
        'views/health_diagnosis_attribute_set_views.xml',
        'views/hr_employee_views.xml',
        'views/res_config_settings_views.xml',
        'views/report_health_diagnosis_templates.xml',
        'views/health_diagnosis_report_views.xml',
        'views/health_disease_outbreak_prediction_views.xml',
        'views/health_disease_outbreak_report_views.xml',
        'views/health_risk_scoring_views.xml',
        'views/health_risk_scoring_report_views.xml',
        'views/health_recommendation_views.xml', 
        'views/symptom_checker_views.xml', 
        'views/menu_health_diagnosis.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
