from . import hr_employee
from . import res_config_settings
from . import health_diagnosis
from . import health_diagnosis_attribute_set
from . import health_diagnosis_attribute_value
from . import health_diagnosis_attribute
from . import health_diagnosis_attribute_line
from . import health_diagnosis_report
from . import health_disease_outbreak_prediction
from . import health_disease_outbreak_report
from . import health_recommendation
from . import health_recommendation_report
from . import health_risk_scoring
from . import health_risk_scoring_report
from . import symptom_checker